project_id = "kyolnraqudwrjjbtxhwx"

[auth.email.template.magic_link]
subject = "Sign in to Workout Lens"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.invite]
subject = "You have been invited to Workout Lens"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your Workout Lens account"
content_path = "./supabase/templates/confirmation.html"
